---

- name: Fail if dependencies are missing
  ansible.builtin.fail:
    msg: >-
      Missing dependencies:
      {{ veracrypt_fedora_dependencies
         | difference(ansible_facts.packages.keys())
         | join(', ')
      }}
  when: veracrypt_fedora_dependencies | difference(ansible_facts.packages.keys()) | length > 0
