---
# SPDX-License-Identifier: MIT-0

- name: Load OS-specific vars
  ansible.builtin.include_vars: "../vars/{{ ansible_facts.distribution | lower }}-{{ ansible_facts.distribution_major_version }}.yml"

- name: Include Debian 13 tasks
  ansible.builtin.include_tasks: setup-debian-13.yml
  when:
    - ansible_facts.distribution == 'Debian'
    - ansible_facts.distribution_major_version | int == 13

- name: Include Fedora 42 tasks
  ansible.builtin.include_tasks: setup-fedora-42.yml
  when:
    - ansible_facts.distribution == 'Fedora'
    - ansible_facts.distribution_major_version | int == 42

- name: Include Fedora 43 tasks
  ansible.builtin.include_tasks: setup-fedora-43.yml
  when:
    - ansible_facts.distribution == 'Fedora'
    - ansible_facts.distribution_major_version | int == 43
