---
# SPDX-License-Identifier: MIT-0

- name: Include Debian tasks
  ansible.builtin.include_tasks: setup-debian.yml
  when:
    - ansible_facts.os_family == 'Debian'

- name: Include RHEL tasks
  ansible.builtin.include_tasks: setup-RedHat.yml
  when:
    - ansible_facts.os_family == 'RedHat'
